### ISSUE TITLE
Setting RGB LEDs can interfere with tunes 

### ISSUE THREAD

**Issue by joshgoebel** [Arduboy/ArduboyPlayTune#1] opened 2016-02-23 03:18 UTC
The conflict is Timer 1 Compare A.

Temp workaround:
Do not use both RGB led and music.

Reference: https://github.com/Arduboy/Arduboy/issues/64

**Comment by MLXXXp** [comment] 2016-07-03 01:50
Using my [ArduboyTones](https://github.com/MLXXXp/ArduboyTones) library is a possible way around this problem.

Should this issue be kept open or should we call it an unfortunate conflict and close it? I've already documented it at the end of the README.md file.

**Comment by joshgoebel** [comment] 2016-07-03 18:49
I don't care, but since it's fixable why not leave it open.  Fixing it by writing ANOTHER library really doesn't count. :-)

**Comment by MLXXXp** [comment] 2016-07-04 00:43
What do you feel the fix would be? I haven't given it much thought, but the one thing I've come up with is:

Change this library so that it uses timer 4, instead of timer 1 (and continues to use timer 3). This would no longer conflict with the RGB LED, which uses timer 0 and timer 1. Timer 4 is only a 10 bit timer instead of being 16 bits, so the prescaling logic may need some work, but it's likely doable.

**Comment by joshgoebel** [comment] 2016-07-04 19:14
I don't really know - using a diff timer or compare register (by making the PWM code piggy back the music), but that feels a little icky - but then there is a reason this was called ArduboyTunes. Using a different timer would be the best use of resources, but would remove a timer that then software couldn't use for something else (which I always hate doing).

My point was just that this is a bug and that it isn't resolved by your creating another library without the same problem - so it should stay open incase someone ever wants to fix it. :-)

**Comment by MLXXXp** [comment] 2016-07-04 19:43
> My point was just that this is a bug and that it isn't resolved by your creating another library without the same problem

Sorry, I didn't mean to imply that. I was just pointing out a fact, but I can see how it could easily have been misinterpreted as me trying to make it a solution that allows this issue to be closed.

My only reason for closing this issue would be what I said later: to just call it a conflict that we don't wish to resolve. Like you, I don't like the idea of using a different timer. It would be nice to leave at least one timer (number 4) free for a sketch itself to use as desired.

To reword my comment above to read the way I intended it:

Should this issue be kept open or should we call it an unfortunate conflict and close it? We could point out to users that the ArduboyTones library could be considered as a possible alternative, for those who wish to have full PWM control of the RGB LED.

**Comment by dunk8888** [comment] 2017-01-10 12:37
Hi is the rgb led common anode or common cathode?

**Comment by MLXXXp** [comment] 2017-01-10 12:42
Common anode.

**Comment by dunk8888** [comment] 2017-01-10 15:27
THANKS ;-)

**Comment by dunk8888** [comment] 2017-01-10 18:45
Hi do you know why the arduboy has read only on the site? you cant post any
more and needed to find out this question + Ime trying to find where ide
1.6.13 puts the updated libraries,as ime changing pins around in arduboy
core for a new clone ime making but the changes dont update,now i remember
before the arduboy library is someplace els ive even deleted the arduboy
library from my libraries folder and games still compile so there is one
hidden that the ide is using where?
Any ideas

**Comment by MLXXXp** [comment] 2018-04-12 19:46
Closing this. The issue is known and documented. A number of other sound generating libraries and functions are available if this conflict is an issue for a sketch.

**Closed as completed by MLXXXp** 2018-04-12 19:46 UTC
